name: T Test
favicon: null
layout_spectrum: 0.2103755136486143
typography_spectrum: 0.2312132481019944
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7976743027102202
  lightness: 0.8601739455480129
  saturation: 0.08062433823943138
  rhythmicContrast: 0.2662635671440512
purpose: []
